	#PACKAGE custom
	#CLASSDEF public

public static void func(String flaggedParam, String notFlaggedParam)

	type String flagged
	type String notFlagged

	// no flag
	do Runtime.start("BA")
	do Runtime.commit()

	// flag for flagged
	do Runtime.start("BA")
	set flagged = ""
	do Runtime.commit()

	// flag for flagged and not notFlagged
	do Runtime.start("BA", "notFlagged")
	set flagged = ""
	set notFlagged = ""
	do Runtime.commit()

	// @psl-lint.RuntimeStart accept="notFlagged"
	do Runtime.start("BA")
	set notFlagged = ""
	do Runtime.commit()

	// no flag
	do Runtime.start("BA")
	type String declaredInside
	set declaredInside = ""
	do Runtime.commit()

	// flag flaggedParam
	do Runtime.start("BA", "notFlaggedParam")
	set flaggedParam = ""
	set notFlaggedParam = ""
	do Runtime.commit()

	// flag notFlaggedTwice once, along with relatedDiagnostics
	type String notFlaggedTwice = ""
	do Runtime.start("BA")
	set notFlaggedTwice = ""
	do Runtime.commit()
	do Runtime.commit()

	type String literal NOLITERAL = ""
	// flag flagged but not NOLITERAL
	do Runtime.start("BA")
	set (flagged, NOLITERAL) = ""
	do Runtime.commit()

	quit
