	#CLASSDEF extends = ZParent

	#PROPERTYDEF	dummy	class = String	position = 2
	#PROPERTYDEF	propInParentAndChild	class = String	position = 3
	#PROPERTYDEF	PROPINCHILD	class = String	position = 4
	#PROPERTYDEF 	detailFile = "B32572"	class = String	private	literal
	/* DOC ----------------------------------------------------------------
	header file name
	** ENDDOC */
	// --------------------------------------------------------------------
public void String zebraMethod()
	/* DOC ----------------------------------------------------------------
	BLABLA
	** ENDDOC */
	type Number thisNumberHasMoreThanTwentyFiveCharacters
	quit
	// --------------------------------------------------------------------
private void String methodInChild()
	/* DOC ----------------------------------------------------------------
	BLABLABLABLA

	** ENDDOC */
	type String y
	type String vString
	type public Number vNumber
	quit
