sudo: false
dist: trusty
language: node_js
node_js:
  - "10"

stages:
  - build
  - name: deploy lint
    if: tag =~ ^lint
  - name: deploy vscode
    if: tag =~ ^vscode

jobs:
  include:
    - stage: build
      script:
        - npm run compile
        - npm run compile-lint
      name: compile
    - script:
        - npm run lint
      name: lint
    - script:
        - npm run test
      name: test

    - stage: deploy lint
      script: cp ./src/pslLint/cli/.npmrc.psl-lint .npmrc && npm run compile-lint
      deploy:
        provider: script
        script: npm publish ./src/pslLint/cli
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
      name: npm

    - stage: deploy vscode
      script: npm run compile && npm i -g vsce && vsce package
      deploy:
        provider: script
        script: vsce publish -p $VSCODE_TOKEN
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
      name: marketplace
