# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code and run tests.

name: Build and Test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24.x'
        cache: 'npm'
    - run: npm install
    - run: npm run build
