# This workflow will build and publish the plugin on tag create

name: Publish vscode-psl

on:
  push:
    tags: 'vscode*'

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm install
    - run: cd src/pslLint/cli && npm install && cd -
      name: Install psl-lint CLI dependencies
    - run: npm run compile
    - run: npm run compile-lint
    - run: npm test
  
  publish:
    needs: test
    name: Publish vscode-psl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm install .
    - run: npm run compile && npm i -g vsce && vsce package
    - env:
          VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN_PUBLISH }}
      run: vsce publish -p $VSCODE_TOKEN
